# Local SDK/NDK/CMake versions to match what's already installed, avoiding
# extra downloads. H.264 is decoded by OpenH264, loaded at runtime from Cisco's
# own binary, which the app downloads on the device (OpenH264.kt): Cisco's
# AVC patent license only covers its binary when it is downloaded separately,
# never bundled. The OpenH264 source is still built here, for its headers only;
# app/build.gradle keeps that libopenh264.so out of the APK. MediaCodec stays
# off: Android 10's decoders hold 3-5 frames, which RDP cannot use.
# FFmpeg/Opus/WebP/JPEG/PNG are off.
# CMAKE_BUILD_TYPE=RelWithDebInfo: without it a debug APK builds FreeRDP at
# -O0, and its NEON/colour code runs several times slower (13 vs 33 frames/s
# at 320% vs 205% CPU on the MatePad SE 11). -O2 still keeps symbols for simpleperf.
COMPILE_API=36
TARGET_API=36
MIN_API=29
NDK_VERSION=30.0.14904198
CMAKE_VERSION=4.1.2
CMAKE_ARGUMENTS=-DWITH_FFMPEG=OFF;-DWITH_OPENH264=ON;-DWITH_OPENH264_LOADING=ON;-DWITH_MEDIACODEC=OFF;-DWITH_OPUS=OFF;-DWITH_WEBP=OFF;-DWITH_JPEG=OFF;-DWITH_PNG=OFF;-DWITH_CJSON=ON;-DWITH_OPENSSL=ON;-DCMAKE_BUILD_TYPE=RelWithDebInfo
ABI_FILTERS=arm64-v8a
