// Slime OS — Brain-side enrollment endpoint
//
// Serves the pairing codes generated by brain/wireguard/pair-peer.sh: a
// Membrane device POSTs a short-lived code here and gets back its WireGuard
// client config, replacing the old manual USB/rescue-mode copy step. This
// is part of the open-source, account-free Connect path -- it deliberately
// does not sit behind Authelia (see brain/caddy/Caddyfile; dashboard.
// slimeos.com is the separate, not-yet-built Slime ID managed path).
//
// Speaks just enough of the Redis RESP protocol by hand (AUTH + GETDEL)
// rather than pulling in a client library: this service sits right next to
// WireGuard peer configs and is reachable from the open internet via Caddy,
// so keeping its dependency graph at zero external packages keeps it fully
// auditable from this one file -- same rationale as membrane/bridge/main.go.
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"os"
	"strings"
	"sync"
	"time"
)

const codeAlphabet = "ABCDEFGHJKMNPQRSTVWXYZ23456789"

func main() {
	listen := flag.String("listen", ":8080", "address to listen on")
	redisAddr := flag.String("redis-addr", "redis:6379", "Redis address")
	redisPassword := flag.String("redis-password", "", "Redis password (defaults to $REDIS_PASSWORD)")
	flag.Parse()

	pw := *redisPassword
	if pw == "" {
		pw = os.Getenv("REDIS_PASSWORD")
	}
	if pw == "" {
		log.Fatal("no Redis password: pass --redis-password or set REDIS_PASSWORD")
	}

	s := &server{
		redisAddr:     *redisAddr,
		redisPassword: pw,
		// 10 req/min/IP: blunts scanning noise, not the primary control --
		// single-use + 15-min TTL on the code itself (pair-peer.sh) is what
		// actually makes brute force infeasible.
		limiter: newRateLimiter(10, time.Minute),
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/pair", s.handlePair)

	log.Printf("slimeos-enroll listening on %s (redis=%s)", *listen, *redisAddr)
	log.Fatal(http.ListenAndServe(*listen, mux))
}

type server struct {
	redisAddr     string
	redisPassword string
	limiter       *rateLimiter
}

type pairRequest struct {
	Code string `json:"code"`
}

type pairResponse struct {
	OK     bool   `json:"ok"`
	Config string `json:"config,omitempty"`
	Error  string `json:"error,omitempty"`
}

func (s *server) handlePair(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// POST with the code in the JSON body, not a GET with it in the URL --
	// Caddy's access log would otherwise persist the pairing code in
	// plaintext on disk.
	ip := clientIP(r)
	if !s.limiter.allow(ip) {
		writeJSON(w, http.StatusTooManyRequests, pairResponse{Error: "rate_limited"})
		return
	}

	var req pairRequest
	if err := json.NewDecoder(io.LimitReader(r.Body, 1024)).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, pairResponse{Error: "bad_request"})
		return
	}

	code := normalizeCode(req.Code)
	if !validCode(code) {
		writeJSON(w, http.StatusBadRequest, pairResponse{Error: "invalid_or_expired"})
		return
	}

	config, err := s.redisGetDel("pair:" + code)
	if err != nil {
		log.Printf("redis error: %v", err)
		writeJSON(w, http.StatusInternalServerError, pairResponse{Error: "internal_error"})
		return
	}
	if config == "" {
		// Same response whether the code never existed, already expired, or
		// was already consumed -- don't give an attacker a distinguishing
		// oracle between "wrong code" and "right code, already used".
		writeJSON(w, http.StatusNotFound, pairResponse{Error: "invalid_or_expired"})
		return
	}

	writeJSON(w, http.StatusOK, pairResponse{OK: true, Config: config})
}

func normalizeCode(raw string) string {
	raw = strings.ToUpper(strings.TrimSpace(raw))
	return strings.ReplaceAll(raw, "-", "")
}

func validCode(code string) bool {
	if len(code) != 8 {
		return false
	}
	for _, c := range code {
		if !strings.ContainsRune(codeAlphabet, c) {
			return false
		}
	}
	return true
}

func clientIP(r *http.Request) string {
	// Caddy is the only hop in front of this service -- the leftmost
	// X-Forwarded-For entry is the real client.
	if xff := r.Header.Get("X-Forwarded-For"); xff != "" {
		return strings.TrimSpace(strings.Split(xff, ",")[0])
	}
	host, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		return r.RemoteAddr
	}
	return host
}

func writeJSON(w http.ResponseWriter, status int, v pairResponse) {
	if status == http.StatusOK {
		v.OK = true
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

// ── Fixed-window per-IP rate limiter ─────────────────────────────────────────
// Deliberately simple (no cleanup goroutine, no LRU): this endpoint sees
// enrollment-scale traffic (a handful of new devices at a time, not a public
// API), so an unbounded-but-slow-growing map is an acceptable trade for
// keeping this file small and dependency-free.

type rateLimiter struct {
	mu     sync.Mutex
	limit  int
	window time.Duration
	counts map[string]*bucket
}

type bucket struct {
	count     int
	windowEnd time.Time
}

func newRateLimiter(limit int, window time.Duration) *rateLimiter {
	return &rateLimiter{limit: limit, window: window, counts: make(map[string]*bucket)}
}

func (r *rateLimiter) allow(key string) bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	now := time.Now()
	b, ok := r.counts[key]
	if !ok || now.After(b.windowEnd) {
		b = &bucket{windowEnd: now.Add(r.window)}
		r.counts[key] = b
	}
	b.count++
	return b.count <= r.limit
}

// ── Minimal RESP client (AUTH + GETDEL only) ────────────────────────────────
// A fresh connection per request, not a pool: traffic here is low-volume
// enough that connection-reuse complexity isn't worth it, and it avoids any
// risk of interleaving commands from concurrent requests on a shared socket.

func (s *server) redisGetDel(key string) (string, error) {
	conn, err := net.DialTimeout("tcp", s.redisAddr, 3*time.Second)
	if err != nil {
		return "", err
	}
	defer conn.Close()
	_ = conn.SetDeadline(time.Now().Add(3 * time.Second))

	w := bufio.NewWriter(conn)
	r := bufio.NewReader(conn)

	if err := respWriteCommand(w, "AUTH", s.redisPassword); err != nil {
		return "", err
	}
	if err := w.Flush(); err != nil {
		return "", err
	}
	if _, err := respReadReply(r); err != nil {
		return "", fmt.Errorf("AUTH failed: %w", err)
	}

	if err := respWriteCommand(w, "GETDEL", key); err != nil {
		return "", err
	}
	if err := w.Flush(); err != nil {
		return "", err
	}
	return respReadReply(r)
}

func respWriteCommand(w *bufio.Writer, args ...string) error {
	if _, err := fmt.Fprintf(w, "*%d\r\n", len(args)); err != nil {
		return err
	}
	for _, a := range args {
		if _, err := fmt.Fprintf(w, "$%d\r\n%s\r\n", len(a), a); err != nil {
			return err
		}
	}
	return nil
}

// respReadReply reads exactly one RESP reply. Sufficient subset for this
// file's needs: simple strings (+), errors (-), and bulk strings ($,
// including the nil-bulk-string $-1 case GETDEL returns on a miss).
func respReadReply(r *bufio.Reader) (string, error) {
	line, err := r.ReadString('\n')
	if err != nil {
		return "", err
	}
	line = strings.TrimRight(line, "\r\n")
	if line == "" {
		return "", fmt.Errorf("empty redis reply")
	}

	switch line[0] {
	case '+':
		return line[1:], nil
	case '-':
		return "", fmt.Errorf("redis error: %s", line[1:])
	case '$':
		var n int
		if _, err := fmt.Sscanf(line[1:], "%d", &n); err != nil {
			return "", err
		}
		if n < 0 {
			return "", nil // nil bulk string -- key missing/expired
		}
		buf := make([]byte, n+2) // payload + trailing \r\n
		if _, err := io.ReadFull(r, buf); err != nil {
			return "", err
		}
		return string(buf[:n]), nil
	default:
		return "", fmt.Errorf("unsupported redis reply: %q", line)
	}
}
